spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gira
    username: postgres
    password: minhthichlag
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop